# Generated by Django 5.2.5 on 2025-09-02 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unigestAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='professeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='unigestAPP.professeur'),
            preserve_default=False,
        ),
    ]
