# Generated by Django 5.2.5 on 2025-08-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unigestAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
