# Generated by Django 5.2.5 on 2025-09-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unigestAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenceretard',
            name='date_enregistrement',
            field=models.DateField(auto_now=True),
        ),
    ]
