# Generated by Django 5.2.5 on 2025-09-25 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unigestAPP', '0002_alter_absenceretard_date_enregistrement'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='filiere',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='emplois', to='unigestAPP.filiere'),
            preserve_default=False,
        ),
    ]
