# Generated by Django 5.2.5 on 2025-08-29 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unigestAPP', '0002_parent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomfiliere', models.CharField(max_length=255)),
                ('DateEnregistrement', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='DateNaissance',
        ),
        migrations.AddField(
            model_name='matiere',
            name='filiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='unigestAPP.filiere'),
            preserve_default=False,
        ),
    ]
